### ISSUE TITLE
Celery not working

### ISSUE THREAD

**Issue by HarleyK1ng** [ohld/django-telegram-bot#20]
periodic tasks can only be started manually one time and never restarts by its own.
console says "Usage: celery worker [OPTIONS]
Try 'celery worker --help' for help.

Error: Invalid value for '-P' / '--pool': <class 'celery.concurrency.prefork.TaskPool'> is not one of 'prefork', 'eventlet', 'gevent', 'solo', 'processes', 'threads'."

Issue occurs only when deploying to dokku, in local containers it works just fine

**Comment by anvarkhamidov** [comment]
Facing the same issue

**Comment by anvarkhamidov** [comment]
@misteraverin @ohld Facing the same issue that said above

**Comment by ohld** [comment]
These issues are caused by breaking changes of the `celery` package. I'll update the command to match the new syntax.
