### ISSUE TITLE
TypeError with arbitrary callback_data

### ISSUE THREAD

**Issue by hsh01** [ohld/django-telegram-bot#35]
Hi, trying to use [example ](https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/arbitrarycallbackdatabot.py) with arbitrary callback_data, but it gives error `TypeError: expected string or bytes-like object`. I just copied all functions to `tgbot/handlers.py` and set all handlers from `main()` in `tgbot/dispatcher.py`. Any solution?

**Comment by shamaevnn** [comment]
@hsh01 It's crucial to provide proper `callback_data` while working with that type of handlers. 
It's difficult to say what is your problem without any example of your code. 

By the way, we updated our template. Now it has a little bit differ structure which is much more convenient for using. Try it out, probably, it will solve your problem 😊
