### ISSUE TITLE
Make migrations folder persistent

### ISSUE THREAD

**Issue by HarleyK1ng** [ohld/django-telegram-bot#36]
Заметил, что при деплое миграции затираются. Может проблема только у меня, но она есть. Подскажите, пожалуйста, решение.
В .gitignore я конечно же добавил папку миграций, иначе в прод улетают мои локальные миграции, что иногда может ломать прод - ведь на локалхосте что только не творится и это нельзя запускать в прод )

**Comment by ohld** [comment]
Изучите, как работают файлы миграций в Django. Папку с миграциями не надо добавлять в .gitignore.
